# version: "3.8"
services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:7-jammy
    ports:
      - "27017:27017"
