# version: "3.8"
services:
  frontend:
    image: tinegagideon/yolo-frontend:1.0.0
    ports:
      - "3000:3000"

  backend:
    image: tinegagideon/yolo-backend:1.0.0
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:7-jammy
    ports:
      - "27017:27017"
