# version: "3.8"
services:
  frontend:
    image: tinegagideon/yolo-frontend:2.0.0
    ports:
      - "80:80"
    networks:
      - frontend

  backend:
    image: tinegagideon/yolo-backend:1.0.0
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - backend

  mongodb:
    image: mongo:7-jammy
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - backend

volumes:
  mongodata:

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
