---
- hosts: all
  become: true

  roles:
    - role: test-connectivity
    - role: update-server
    - role: install-docker
    - role: clone-repo
    - role: setup-frontend
    - role: setup-mongodb
    - role: setup-backend
    - role: run-docker-compose
