apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-statefulset
spec:
  selector:
    matchLabels:
      app: mongo
  serviceName: mongo
  replicas: 2
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:7-jammy
        ports:
          - containerPort: 27017
        volumeMounts:
          - name: mongodata
            mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongodata
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi


---

apiVersion: v1
kind: Service
metadata:
  name:  mongodb-service
spec:
  selector:
    app:  mongo
  ports:
  - port: 27017
    targetPort: 27017