apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-client
spec:
  selector:
    matchLabels:
      app: yolo-client
  template:
    metadata:
      labels:
        app: yolo-client
    spec:
      containers:
      - name: yolo-client
        image: tinegagideon/yolo-client:1.0.4
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

        env:
          - name: REACT_APP_API_BASE_URL 
            value: http://yolo-backend-service:5000

            

---
apiVersion: v1
kind: Service
metadata:
  name: yolo-client-service
spec:
  selector:
    app: yolo-client
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 80
